---
- name: Deploy Artifact to Localhost
  hosts: localhost
  become: true

  tasks:
    - name: Copy the artifact to the target location
      copy:
        src: "/var/lib/jenkins/workspace/6prog/target/hello-maven-1.0-SNAPSHOT.jar"
        dest: "/home/nanda_123/t.jar"
